apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: {{ .Values.server.service.nodePort }}
  selector:
    app.kubernetes.io/name: argocd-server